In [1]:
import requests
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt

In [ ]:
################################################################################################################################
#                                                      GLMR                                                                    #
################################################################################################################################

In [2]:
url = 'https://rest.coinapi.io/v1/ohlcv/KRAKEN_SPOT_GLMR_USD/history?period_id=1DAY&time_start=2022-01-11T00:00:00&limit=500'

headers = {
#   'Accepts': 'application/json',
  # please create api key or use hamza's personal CoinAPI key listed on Chapter 7.1 Personal API Keys section of thesis
  'X-CoinAPI-Key': ''
}

response = requests.get(url, headers=headers)

In [3]:
print(response)

<Response [200]>


In [4]:
data = json.loads(response.text)
print(data)

[{'time_period_start': '2022-01-11T00:00:00.0000000Z', 'time_period_end': '2022-01-12T00:00:00.0000000Z', 'time_open': '2022-01-11T19:35:40.9460000Z', 'time_close': '2022-01-11T23:58:43.6750000Z', 'price_open': 19.0, 'price_high': 19.0, 'price_low': 11.0, 'price_close': 11.955, 'volume_traded': 50170.34795612, 'trades_count': 661}, {'time_period_start': '2022-01-12T00:00:00.0000000Z', 'time_period_end': '2022-01-13T00:00:00.0000000Z', 'time_open': '2022-01-12T00:01:53.8930000Z', 'time_close': '2022-01-12T23:59:24.0560000Z', 'price_open': 11.901, 'price_high': 13.0, 'price_low': 8.282, 'price_close': 8.987, 'volume_traded': 523059.6863931, 'trades_count': 4109}, {'time_period_start': '2022-01-13T00:00:00.0000000Z', 'time_period_end': '2022-01-14T00:00:00.0000000Z', 'time_open': '2022-01-13T00:00:38.1960000Z', 'time_close': '2022-01-13T23:59:28.5540000Z', 'price_open': 8.99, 'price_high': 14.6, 'price_low': 8.559, 'price_close': 11.66, 'volume_traded': 490644.56856553, 'trades_count': 52

In [5]:
df_json = response.json()
df_glmr = pd.DataFrame.from_dict(df_json)
df_glmr

time_period_start               time_period_end  \
0    2022-01-11T00:00:00.0000000Z  2022-01-12T00:00:00.0000000Z   
1    2022-01-12T00:00:00.0000000Z  2022-01-13T00:00:00.0000000Z   
2    2022-01-13T00:00:00.0000000Z  2022-01-14T00:00:00.0000000Z   
3    2022-01-14T00:00:00.0000000Z  2022-01-15T00:00:00.0000000Z   
4    2022-01-15T00:00:00.0000000Z  2022-01-16T00:00:00.0000000Z   
..                            ...                           ...   
262  2022-09-30T00:00:00.0000000Z  2022-10-01T00:00:00.0000000Z   
263  2022-10-01T00:00:00.0000000Z  2022-10-02T00:00:00.0000000Z   
264  2022-10-02T00:00:00.0000000Z  2022-10-03T00:00:00.0000000Z   
265  2022-10-03T00:00:00.0000000Z  2022-10-04T00:00:00.0000000Z   
266  2022-10-04T00:00:00.0000000Z  2022-10-05T00:00:00.0000000Z   

                        time_open                    time_close  price_open  \
0    2022-01-11T19:35:40.9460000Z  2022-01-11T23:58:43.6750000Z      19.000   
1    2022-01-12T00:01:53.8930000Z  2022-01-12T23:59:24.0560000Z      11.901   
2    2022-01-13T00:00:38.1960000Z  2022-01-13T23:59:28.5540000Z       8.990   
3    2022-01-14T00:05:06.4800000Z  2022-01-14T23:55:31.5530000Z      11.440   
4    2022-01-15T00:00:11.5930000Z  2022-01-15T23:59:52.8460000Z      13.373   
..                            ...                           ...         ...   
262  2022-09-30T01:50:31.2130000Z  2022-09-30T23:48:27.9970000Z       0.451   
263  2022-10-01T02:12:15.4110000Z  2022-10-01T23:59:22.2340000Z       0.444   
264  2022-10-02T00:02:31.8220000Z  2022-10-02T23:06:34.8500000Z       0.474   
265  2022-10-03T01:33:46.4050000Z  2022-10-03T23:49:26.8850000Z       0.454   
266  2022-10-04T00:16:27.1050000Z  2022-10-04T20:58:43.1450000Z       0.460   

     price_high  price_low  price_close  volume_traded  trades_count  
0        19.000     11.000       11.955   50170.347956           661  
1        13.000      8.282        8.987  523059.686393          4109  
2        14.600      8.559       11.660  490644.568566          5269  
3        15.990     11.278       13.432  361019.989280          4048  
4        14.240     12.391       12.650  121468.167543          1374  
..          ...        ...          ...            ...           ...  
262       0.458      0.424        0.444  103732.001067           179  
263       0.481      0.441        0.470  217359.823151           249  
264       0.484      0.448        0.448  235291.770219           232  
265       0.464      0.440        0.460   98926.669169           193  
266       0.620      0.455        0.476  150633.250410           188  

[267 rows x 10 columns]

In [6]:
df_glmr['symbol'] = 'GLMR'
df_glmr['currency'] = 'USD'

In [7]:
df_glmr.dtypes

time_period_start     object
time_period_end       object
time_open             object
time_close            object
price_open           float64
price_high           float64
price_low            float64
price_close          float64
volume_traded        float64
trades_count           int64
symbol                object
currency              object
dtype: object

In [8]:
df_glmr = df_glmr.drop(columns=['time_period_end'])

In [9]:
df_glmr = df_glmr.rename(columns={"time_period_start" : "date"})

In [10]:
df_glmr_converted = df_glmr.convert_dtypes()


In [11]:
df_glmr_converted.dtypes

date              string
time_open         string
time_close        string
price_open       Float64
price_high       Float64
price_low        Float64
price_close      Float64
volume_traded    Float64
trades_count       Int64
symbol            string
currency          string
dtype: object

In [ ]:
# date cleaning!

In [12]:
df_glmr_converted['date'] = df_glmr_converted['date'].str.split('T').str.get(0)

In [13]:
df_glmr_converted['time_open'] = df_glmr_converted['time_open'].str.split('T').str.get(1)

In [14]:
df_glmr_converted['time_open'] = df_glmr_converted['time_open'].str.replace('Z', '')
df_glmr_converted

date         time_open                    time_close  price_open  \
0    2022-01-11  19:35:40.9460000  2022-01-11T23:58:43.6750000Z        19.0   
1    2022-01-12  00:01:53.8930000  2022-01-12T23:59:24.0560000Z      11.901   
2    2022-01-13  00:00:38.1960000  2022-01-13T23:59:28.5540000Z        8.99   
3    2022-01-14  00:05:06.4800000  2022-01-14T23:55:31.5530000Z       11.44   
4    2022-01-15  00:00:11.5930000  2022-01-15T23:59:52.8460000Z      13.373   
..          ...               ...                           ...         ...   
262  2022-09-30  01:50:31.2130000  2022-09-30T23:48:27.9970000Z       0.451   
263  2022-10-01  02:12:15.4110000  2022-10-01T23:59:22.2340000Z       0.444   
264  2022-10-02  00:02:31.8220000  2022-10-02T23:06:34.8500000Z       0.474   
265  2022-10-03  01:33:46.4050000  2022-10-03T23:49:26.8850000Z       0.454   
266  2022-10-04  00:16:27.1050000  2022-10-04T20:58:43.1450000Z        0.46   

     price_high  price_low  price_close  volume_traded  trades_count symbol  \
0          19.0       11.0       11.955   50170.347956           661   GLMR   
1          13.0      8.282        8.987  523059.686393          4109   GLMR   
2          14.6      8.559        11.66  490644.568566          5269   GLMR   
3         15.99     11.278       13.432   361019.98928          4048   GLMR   
4         14.24     12.391        12.65  121468.167543          1374   GLMR   
..          ...        ...          ...            ...           ...    ...   
262       0.458      0.424        0.444  103732.001067           179   GLMR   
263       0.481      0.441         0.47  217359.823151           249   GLMR   
264       0.484      0.448        0.448  235291.770219           232   GLMR   
265       0.464       0.44         0.46   98926.669169           193   GLMR   
266        0.62      0.455        0.476   150633.25041           188   GLMR   

    currency  
0        USD  
1        USD  
2        USD  
3        USD  
4        USD  
..       ...  
262      USD  
263      USD  
264      USD  
265      USD  
266      USD  

[267 rows x 11 columns]

In [15]:
df_glmr_converted['time_close'] = df_glmr_converted['time_close'].str.split('T').str.get(1)

In [16]:
df_glmr_converted['time_close'] = df_glmr_converted['time_close'].str.replace('Z', '')
df_glmr_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  19:35:40.9460000  23:58:43.6750000        19.0        19.0   
1    2022-01-12  00:01:53.8930000  23:59:24.0560000      11.901        13.0   
2    2022-01-13  00:00:38.1960000  23:59:28.5540000        8.99        14.6   
3    2022-01-14  00:05:06.4800000  23:55:31.5530000       11.44       15.99   
4    2022-01-15  00:00:11.5930000  23:59:52.8460000      13.373       14.24   
..          ...               ...               ...         ...         ...   
262  2022-09-30  01:50:31.2130000  23:48:27.9970000       0.451       0.458   
263  2022-10-01  02:12:15.4110000  23:59:22.2340000       0.444       0.481   
264  2022-10-02  00:02:31.8220000  23:06:34.8500000       0.474       0.484   
265  2022-10-03  01:33:46.4050000  23:49:26.8850000       0.454       0.464   
266  2022-10-04  00:16:27.1050000  20:58:43.1450000        0.46        0.62   

     price_low  price_close  volume_traded  trades_count symbol currency  
0         11.0       11.955   50170.347956           661   GLMR      USD  
1        8.282        8.987  523059.686393          4109   GLMR      USD  
2        8.559        11.66  490644.568566          5269   GLMR      USD  
3       11.278       13.432   361019.98928          4048   GLMR      USD  
4       12.391        12.65  121468.167543          1374   GLMR      USD  
..         ...          ...            ...           ...    ...      ...  
262      0.424        0.444  103732.001067           179   GLMR      USD  
263      0.441         0.47  217359.823151           249   GLMR      USD  
264      0.448        0.448  235291.770219           232   GLMR      USD  
265       0.44         0.46   98926.669169           193   GLMR      USD  
266      0.455        0.476   150633.25041           188   GLMR      USD  

[267 rows x 11 columns]

In [ ]:
# get glmr csv before prediction column

In [17]:
df_glmr_converted.to_csv('glmr_original.csv', encoding='utf-8', index=False)

In [18]:
projection = 7

In [19]:
# create new column called prediction and add close price 'n' days into future with aim of predicting 
df_glmr_converted['prediction_7_days'] = df_glmr_converted[['price_close']].shift(-projection)
df_glmr_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  19:35:40.9460000  23:58:43.6750000        19.0        19.0   
1    2022-01-12  00:01:53.8930000  23:59:24.0560000      11.901        13.0   
2    2022-01-13  00:00:38.1960000  23:59:28.5540000        8.99        14.6   
3    2022-01-14  00:05:06.4800000  23:55:31.5530000       11.44       15.99   
4    2022-01-15  00:00:11.5930000  23:59:52.8460000      13.373       14.24   
..          ...               ...               ...         ...         ...   
262  2022-09-30  01:50:31.2130000  23:48:27.9970000       0.451       0.458   
263  2022-10-01  02:12:15.4110000  23:59:22.2340000       0.444       0.481   
264  2022-10-02  00:02:31.8220000  23:06:34.8500000       0.474       0.484   
265  2022-10-03  01:33:46.4050000  23:49:26.8850000       0.454       0.464   
266  2022-10-04  00:16:27.1050000  20:58:43.1450000        0.46        0.62   

     price_low  price_close  volume_traded  trades_count symbol currency  \
0         11.0       11.955   50170.347956           661   GLMR      USD   
1        8.282        8.987  523059.686393          4109   GLMR      USD   
2        8.559        11.66  490644.568566          5269   GLMR      USD   
3       11.278       13.432   361019.98928          4048   GLMR      USD   
4       12.391        12.65  121468.167543          1374   GLMR      USD   
..         ...          ...            ...           ...    ...      ...   
262      0.424        0.444  103732.001067           179   GLMR      USD   
263      0.441         0.47  217359.823151           249   GLMR      USD   
264      0.448        0.448  235291.770219           232   GLMR      USD   
265       0.44         0.46   98926.669169           193   GLMR      USD   
266      0.455        0.476   150633.25041           188   GLMR      USD   

    prediction_7_days  
0                9.21  
1              10.193  
2                9.77  
3               8.647  
4               7.392  
..                ...  
262               NaN  
263               NaN  
264               NaN  
265               NaN  
266               NaN  

[267 rows x 12 columns]

In [20]:
df_glmr_converted.head(8)

date         time_open        time_close  price_open  price_high  \
0  2022-01-11  19:35:40.9460000  23:58:43.6750000        19.0        19.0   
1  2022-01-12  00:01:53.8930000  23:59:24.0560000      11.901        13.0   
2  2022-01-13  00:00:38.1960000  23:59:28.5540000        8.99        14.6   
3  2022-01-14  00:05:06.4800000  23:55:31.5530000       11.44       15.99   
4  2022-01-15  00:00:11.5930000  23:59:52.8460000      13.373       14.24   
5  2022-01-16  00:00:14.9400000  23:59:36.1770000       12.65      12.792   
6  2022-01-17  00:00:37.3260000  23:58:37.0710000      10.505      11.132   
7  2022-01-18  00:00:28.4210000  23:58:24.1770000      10.061       10.26   

   price_low  price_close  volume_traded  trades_count symbol currency  \
0       11.0       11.955   50170.347956           661   GLMR      USD   
1      8.282        8.987  523059.686393          4109   GLMR      USD   
2      8.559        11.66  490644.568566          5269   GLMR      USD   
3     11.278       13.432   361019.98928          4048   GLMR      USD   
4     12.391        12.65  121468.167543          1374   GLMR      USD   
5     10.402       10.408  162004.674801          1557   GLMR      USD   
6      9.632       10.038  157633.896802          1947   GLMR      USD   
7      8.641         9.21  233404.779121          2547   GLMR      USD   

  prediction_7_days  
0              9.21  
1            10.193  
2              9.77  
3             8.647  
4             7.392  
5             8.018  
6             7.417  
7             7.769

In [21]:
df_glmr_converted.tail(9)

date         time_open        time_close  price_open  price_high  \
258  2022-09-26  00:11:45.4870000  23:53:02.3810000       0.466       0.482   
259  2022-09-27  00:11:24.1890000  23:40:41.2230000       0.468       0.487   
260  2022-09-28  00:17:43.4320000  23:37:22.5850000       0.462       0.462   
261  2022-09-29  00:08:06.8870000  21:54:52.5360000       0.458       0.471   
262  2022-09-30  01:50:31.2130000  23:48:27.9970000       0.451       0.458   
263  2022-10-01  02:12:15.4110000  23:59:22.2340000       0.444       0.481   
264  2022-10-02  00:02:31.8220000  23:06:34.8500000       0.474       0.484   
265  2022-10-03  01:33:46.4050000  23:49:26.8850000       0.454       0.464   
266  2022-10-04  00:16:27.1050000  20:58:43.1450000        0.46        0.62   

     price_low  price_close  volume_traded  trades_count symbol currency  \
258      0.447        0.468   82322.820592           146   GLMR      USD   
259      0.452        0.461  207239.192636           243   GLMR      USD   
260      0.441        0.453   54097.298283           114   GLMR      USD   
261      0.445        0.454  156379.619729           197   GLMR      USD   
262      0.424        0.444  103732.001067           179   GLMR      USD   
263      0.441         0.47  217359.823151           249   GLMR      USD   
264      0.448        0.448  235291.770219           232   GLMR      USD   
265       0.44         0.46   98926.669169           193   GLMR      USD   
266      0.455        0.476   150633.25041           188   GLMR      USD   

    prediction_7_days  
258              0.46  
259             0.476  
260              <NA>  
261              <NA>  
262              <NA>  
263              <NA>  
264              <NA>  
265              <NA>  
266              <NA>

In [ ]:
# MAKE SURE SAVE COPY ON LOCAL MACHINE!!

In [22]:
df_glmr_converted.to_csv('glmr_prediction.csv', encoding='utf-8', index=False)

In [23]:
# test independent dataset (X) = [price_open, price_high, price_low, price_close,volume_traded, trade_count]
X = np.array(df_glmr_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])

In [24]:
X

array([[19.0, 19.0, 11.0, 11.955, 50170.34795612, 661],
       [11.901, 13.0, 8.282, 8.987, 523059.6863931, 4109],
       [8.99, 14.6, 8.559, 11.66, 490644.56856553, 5269],
       ...,
       [0.474, 0.484, 0.448, 0.448, 235291.77021856, 232],
       [0.454, 0.464, 0.44, 0.46, 98926.66916934, 193],
       [0.46, 0.62, 0.455, 0.476, 150633.25040961, 188]], dtype=object)

In [25]:
X = X[:-projection]

In [26]:
X

array([[19.0, 19.0, 11.0, 11.955, 50170.34795612, 661],
       [11.901, 13.0, 8.282, 8.987, 523059.6863931, 4109],
       [8.99, 14.6, 8.559, 11.66, 490644.56856553, 5269],
       ...,
       [0.455, 0.487, 0.453, 0.465, 211945.56332624, 239],
       [0.466, 0.482, 0.447, 0.468, 82322.82059233, 146],
       [0.468, 0.487, 0.452, 0.461, 207239.19263623, 243]], dtype=object)

In [27]:
# create the dependent dataset (y)
y = df_glmr_converted['prediction_7_days'].values

In [28]:
y

array([9.21, 10.193, 9.77, 8.647, 7.392, 8.018, 7.417, 7.769, 7.333,
       6.617, 6.452, 6.173, 5.737, 5.389, 5.365, 5.081, 4.748, 5.748,
       5.769, 6.143, 6.287, 5.831, 5.908, 5.533, 5.157, 4.904, 4.721,
       4.666, 5.179, 5.046, 4.316, 3.889, 3.675, 2.828, 2.332, 2.436,
       2.27, 2.18, 2.39, 2.581, 2.358, 2.664, 2.626, 2.895, 3.084, 3.09,
       2.927, 2.702, 2.56, 2.467, 2.61, 2.532, 2.42, 2.375, 2.25, 2.368,
       2.237, 2.572, 2.404, 2.369, 2.85, 2.68, 2.763, 2.762, 2.791, 2.846,
       2.746, 2.775, 2.864, 3.061, 3.305, 3.313, 3.115, 3.47, 5.046,
       5.278, 5.054, 4.347, 3.75, 4.07, 3.733, 3.955, 4.001, 3.385, 3.674,
       3.947, 3.787, 4.042, 4.238, 3.845, 4.174, 4.212, 4.076, 3.882,
       3.737, 3.638, 3.298, 3.484, 3.066, 2.992, 2.997, 2.647, 2.382,
       2.535, 2.497, 2.449, 2.764, 2.445, 2.327, 2.218, 2.108, 1.7, 1.721,
       1.223, 1.133, 1.194, 1.23, 1.412, 1.289, 1.399, 1.105, 1.208,
       1.128, 1.177, 1.237, 1.161, 1.391, 1.299, 1.163, 1.17, 1.213,
   

In [29]:
y = y[:-projection]

In [30]:
y

array([9.21, 10.193, 9.77, 8.647, 7.392, 8.018, 7.417, 7.769, 7.333,
       6.617, 6.452, 6.173, 5.737, 5.389, 5.365, 5.081, 4.748, 5.748,
       5.769, 6.143, 6.287, 5.831, 5.908, 5.533, 5.157, 4.904, 4.721,
       4.666, 5.179, 5.046, 4.316, 3.889, 3.675, 2.828, 2.332, 2.436,
       2.27, 2.18, 2.39, 2.581, 2.358, 2.664, 2.626, 2.895, 3.084, 3.09,
       2.927, 2.702, 2.56, 2.467, 2.61, 2.532, 2.42, 2.375, 2.25, 2.368,
       2.237, 2.572, 2.404, 2.369, 2.85, 2.68, 2.763, 2.762, 2.791, 2.846,
       2.746, 2.775, 2.864, 3.061, 3.305, 3.313, 3.115, 3.47, 5.046,
       5.278, 5.054, 4.347, 3.75, 4.07, 3.733, 3.955, 4.001, 3.385, 3.674,
       3.947, 3.787, 4.042, 4.238, 3.845, 4.174, 4.212, 4.076, 3.882,
       3.737, 3.638, 3.298, 3.484, 3.066, 2.992, 2.997, 2.647, 2.382,
       2.535, 2.497, 2.449, 2.764, 2.445, 2.327, 2.218, 2.108, 1.7, 1.721,
       1.223, 1.133, 1.194, 1.23, 1.412, 1.289, 1.399, 1.105, 1.208,
       1.128, 1.177, 1.237, 1.161, 1.391, 1.299, 1.163, 1.17, 1.213,
   

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [32]:
# split data into 75% training and 25% testing datasets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

In [33]:
# create and train the model for glmr

lin_reg_glmr = LinearRegression()

In [34]:
# train the model

lin_reg_glmr.fit(X_train, y_train)

LinearRegression()

In [35]:
# test the model using score

lin_reg_glmr_confidence = lin_reg_glmr.score(X_test, y_test)
print('Linear Regression Confidence:', lin_reg_glmr_confidence)

Linear Regression Confidence: 0.88703973387744


In [36]:
# create a variable called x_projection and set it equal to last 7 rows of data from original dataset

x_projection = np.array(df_glmr_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])[-projection:]

print(x_projection)

[[0.462 0.462 0.441 0.453 54097.29828338 114]
 [0.458 0.471 0.445 0.454 156379.61972889 197]
 [0.451 0.458 0.424 0.444 103732.00106724 179]
 [0.444 0.481 0.441 0.47 217359.82315079 249]
 [0.474 0.484 0.448 0.448 235291.77021856 232]
 [0.454 0.464 0.44 0.46 98926.66916934 193]
 [0.46 0.62 0.455 0.476 150633.25040961 188]]


In [37]:
# print the linear regression models prediction for next 7 days

lin_reg_glmr_prediction = lin_reg_glmr.predict(x_projection)

In [38]:
print("below is model prediction for glmr price_close for next 7 days - 05/10/2022 to 11/10/2022")

below is model prediction for glmr price_close for next 7 days - 05/10/2022 to 11/10/2022


In [39]:
print(lin_reg_glmr_prediction)

[0.69437344 0.67480182 0.68318372 0.67079184 0.66501188 0.68845974
 0.68483855]


In [40]:
dates = ['2022-10-05', '2022-10-06', '2022-10-07', '2022-10-08', '2022-10-09', '2022-10-10', '2022-10-11']

In [41]:
df_glmr_pred = pd.DataFrame({'date': dates, 'predicted_price_close': lin_reg_glmr_prediction})

In [42]:
df_glmr_pred

date  predicted_price_close
0  2022-10-05               0.694373
1  2022-10-06               0.674802
2  2022-10-07               0.683184
3  2022-10-08               0.670792
4  2022-10-09               0.665012
5  2022-10-10               0.688460
6  2022-10-11               0.684839

In [ ]:
# MAKE SURE TO SAVE COPY OF THIS THAT INCLUDES SYMBOL AND CURRENCY!!

In [43]:
df_glmr_pred.to_csv('glmr_7_day_model_prediction.csv', encoding='utf-8', index=False)

In [ ]:
# EVERY DAY I MANUALLY GET PRICE AND ONCE 7 DAYS ARE PREDICTED FOR THEN WE COMPARE PREDICTED VS ACTUAL ON GRAPH
# RECALCLUATE SCORE/DELTA
# THIS ASWELL AS SOCIAL MEDIA SECTION WILL MAKE UP PRACTICAL!!!!

In [ ]:
###############################################################################################################################
#                                                            BTC                                                              # 
###############################################################################################################################

In [44]:
url = 'https://rest.coinapi.io/v1/ohlcv/BITSTAMP_SPOT_BTC_USD/history?period_id=1DAY&time_start=2022-01-11T00:00:00&limit=500'
response = requests.get(url, headers=headers)

print(response)

data = json.loads(response.text)
print(data)

df_json = response.json()
df_btc = pd.DataFrame.from_dict(df_json)

df_btc['symbol'] = 'BTC'
df_btc['currency'] = 'USD'
df_btc

<Response [200]>
[{'time_period_start': '2022-01-11T00:00:00.0000000Z', 'time_period_end': '2022-01-12T00:00:00.0000000Z', 'time_open': '2022-01-11T00:00:00.2580000Z', 'time_close': '2022-01-11T23:59:15.2140000Z', 'price_open': 41842.22, 'price_high': 43144.74, 'price_low': 41284.11, 'price_close': 42736.0, 'volume_traded': 2442.65415081, 'trades_count': 23131}, {'time_period_start': '2022-01-12T00:00:00.0000000Z', 'time_period_end': '2022-01-13T00:00:00.0000000Z', 'time_open': '2022-01-12T00:00:13.0980000Z', 'time_close': '2022-01-12T23:59:45.5900000Z', 'price_open': 42754.44, 'price_high': 44337.26, 'price_low': 42471.17, 'price_close': 43933.5, 'volume_traded': 2411.97995648, 'trades_count': 19850}, {'time_period_start': '2022-01-13T00:00:00.0000000Z', 'time_period_end': '2022-01-14T00:00:00.0000000Z', 'time_open': '2022-01-13T00:00:00.4050000Z', 'time_close': '2022-01-13T23:59:50.1280000Z', 'price_open': 43935.01, 'price_high': 44456.34, 'price_low': 42321.0, 'price_close': 42571.9

time_period_start               time_period_end  \
0    2022-01-11T00:00:00.0000000Z  2022-01-12T00:00:00.0000000Z   
1    2022-01-12T00:00:00.0000000Z  2022-01-13T00:00:00.0000000Z   
2    2022-01-13T00:00:00.0000000Z  2022-01-14T00:00:00.0000000Z   
3    2022-01-14T00:00:00.0000000Z  2022-01-15T00:00:00.0000000Z   
4    2022-01-15T00:00:00.0000000Z  2022-01-16T00:00:00.0000000Z   
..                            ...                           ...   
262  2022-09-30T00:00:00.0000000Z  2022-10-01T00:00:00.0000000Z   
263  2022-10-01T00:00:00.0000000Z  2022-10-02T00:00:00.0000000Z   
264  2022-10-02T00:00:00.0000000Z  2022-10-03T00:00:00.0000000Z   
265  2022-10-03T00:00:00.0000000Z  2022-10-04T00:00:00.0000000Z   
266  2022-10-04T00:00:00.0000000Z  2022-10-05T00:00:00.0000000Z   

                        time_open                    time_close  price_open  \
0    2022-01-11T00:00:00.2580000Z  2022-01-11T23:59:15.2140000Z    41842.22   
1    2022-01-12T00:00:13.0980000Z  2022-01-12T23:59:45.5900000Z    42754.44   
2    2022-01-13T00:00:00.4050000Z  2022-01-13T23:59:50.1280000Z    43935.01   
3    2022-01-14T00:00:02.3290000Z  2022-01-14T23:59:29.7940000Z    42579.44   
4    2022-01-15T00:00:00.5280000Z  2022-01-15T23:59:56.2490000Z    43085.76   
..                            ...                           ...         ...   
262  2022-09-30T00:00:01.4850000Z  2022-09-30T23:59:25.3810000Z    19593.00   
263  2022-10-01T00:00:16.2820000Z  2022-10-01T23:59:51.3860000Z    19419.00   
264  2022-10-02T00:00:45.4960000Z  2022-10-02T23:59:24.7860000Z    19306.00   
265  2022-10-03T00:00:03.3860000Z  2022-10-03T23:59:45.1600000Z    19060.00   
266  2022-10-04T00:00:26.2490000Z  2022-10-04T21:02:44.3680000Z    19633.00   

     price_high  price_low  price_close  volume_traded  trades_count symbol  \
0      43144.74   41284.11     42736.00    2442.654151         23131    BTC   
1      44337.26   42471.17     43933.50    2411.979956         19850    BTC   
2      44456.34   42321.00     42571.94    1993.883243         17232    BTC   
3      43468.95   41782.21     43102.35    1386.232116         15936    BTC   
4      43826.80   42387.86     43102.01     692.751523         10172    BTC   
..          ...        ...          ...            ...           ...    ...   
262    20171.00   19152.00     19425.00    2412.929951         13609    BTC   
263    19484.00   19174.00     19312.00     378.442427          6342    BTC   
264    19395.00   18931.00     19051.00     517.932825          4874    BTC   
265    19715.00   18975.00     19636.00    1109.131767         10001    BTC   
266    20469.00   19497.00     20376.00    1980.593068         13254    BTC   

    currency  
0        USD  
1        USD  
2        USD  
3        USD  
4        USD  
..       ...  
262      USD  
263      USD  
264      USD  
265      USD  
266      USD  

[267 rows x 12 columns]

In [45]:
df_btc_converted = df_btc.convert_dtypes()

In [46]:
df_btc_converted.dtypes

time_period_start     string
time_period_end       string
time_open             string
time_close            string
price_open           Float64
price_high           Float64
price_low            Float64
price_close          Float64
volume_traded        Float64
trades_count           Int64
symbol                string
currency              string
dtype: object

In [ ]:
# CLEANING

In [47]:
df_btc_converted = df_btc_converted.drop(columns=['time_period_end'])
df_btc_converted = df_btc_converted.rename(columns={"time_period_start" : "date"})

In [48]:
df_btc_converted

date                     time_open  \
0    2022-01-11T00:00:00.0000000Z  2022-01-11T00:00:00.2580000Z   
1    2022-01-12T00:00:00.0000000Z  2022-01-12T00:00:13.0980000Z   
2    2022-01-13T00:00:00.0000000Z  2022-01-13T00:00:00.4050000Z   
3    2022-01-14T00:00:00.0000000Z  2022-01-14T00:00:02.3290000Z   
4    2022-01-15T00:00:00.0000000Z  2022-01-15T00:00:00.5280000Z   
..                            ...                           ...   
262  2022-09-30T00:00:00.0000000Z  2022-09-30T00:00:01.4850000Z   
263  2022-10-01T00:00:00.0000000Z  2022-10-01T00:00:16.2820000Z   
264  2022-10-02T00:00:00.0000000Z  2022-10-02T00:00:45.4960000Z   
265  2022-10-03T00:00:00.0000000Z  2022-10-03T00:00:03.3860000Z   
266  2022-10-04T00:00:00.0000000Z  2022-10-04T00:00:26.2490000Z   

                       time_close  price_open  price_high  price_low  \
0    2022-01-11T23:59:15.2140000Z    41842.22    43144.74   41284.11   
1    2022-01-12T23:59:45.5900000Z    42754.44    44337.26   42471.17   
2    2022-01-13T23:59:50.1280000Z    43935.01    44456.34    42321.0   
3    2022-01-14T23:59:29.7940000Z    42579.44    43468.95   41782.21   
4    2022-01-15T23:59:56.2490000Z    43085.76     43826.8   42387.86   
..                            ...         ...         ...        ...   
262  2022-09-30T23:59:25.3810000Z     19593.0     20171.0    19152.0   
263  2022-10-01T23:59:51.3860000Z     19419.0     19484.0    19174.0   
264  2022-10-02T23:59:24.7860000Z     19306.0     19395.0    18931.0   
265  2022-10-03T23:59:45.1600000Z     19060.0     19715.0    18975.0   
266  2022-10-04T21:02:44.3680000Z     19633.0     20469.0    19497.0   

     price_close  volume_traded  trades_count symbol currency  
0        42736.0    2442.654151         23131    BTC      USD  
1        43933.5    2411.979956         19850    BTC      USD  
2       42571.94    1993.883243         17232    BTC      USD  
3       43102.35    1386.232116         15936    BTC      USD  
4       43102.01     692.751523         10172    BTC      USD  
..           ...            ...           ...    ...      ...  
262      19425.0    2412.929951         13609    BTC      USD  
263      19312.0     378.442427          6342    BTC      USD  
264      19051.0     517.932825          4874    BTC      USD  
265      19636.0    1109.131767         10001    BTC      USD  
266      20376.0    1980.593068         13254    BTC      USD  

[267 rows x 11 columns]

In [49]:
df_btc_converted['date'] = df_btc_converted['date'].str.split('T').str.get(0)

In [50]:
df_btc_converted['time_open'] = df_btc_converted['time_open'].str.split('T').str.get(1)
df_btc_converted['time_open'] = df_btc_converted['time_open'].str.replace('Z', '')
df_btc_converted['time_close'] = df_btc_converted['time_close'].str.split('T').str.get(1)
df_btc_converted['time_close'] = df_btc_converted['time_close'].str.replace('Z', '')
df_btc_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:00.2580000  23:59:15.2140000    41842.22    43144.74   
1    2022-01-12  00:00:13.0980000  23:59:45.5900000    42754.44    44337.26   
2    2022-01-13  00:00:00.4050000  23:59:50.1280000    43935.01    44456.34   
3    2022-01-14  00:00:02.3290000  23:59:29.7940000    42579.44    43468.95   
4    2022-01-15  00:00:00.5280000  23:59:56.2490000    43085.76     43826.8   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:00:01.4850000  23:59:25.3810000     19593.0     20171.0   
263  2022-10-01  00:00:16.2820000  23:59:51.3860000     19419.0     19484.0   
264  2022-10-02  00:00:45.4960000  23:59:24.7860000     19306.0     19395.0   
265  2022-10-03  00:00:03.3860000  23:59:45.1600000     19060.0     19715.0   
266  2022-10-04  00:00:26.2490000  21:02:44.3680000     19633.0     20469.0   

     price_low  price_close  volume_traded  trades_count symbol currency  
0     41284.11      42736.0    2442.654151         23131    BTC      USD  
1     42471.17      43933.5    2411.979956         19850    BTC      USD  
2      42321.0     42571.94    1993.883243         17232    BTC      USD  
3     41782.21     43102.35    1386.232116         15936    BTC      USD  
4     42387.86     43102.01     692.751523         10172    BTC      USD  
..         ...          ...            ...           ...    ...      ...  
262    19152.0      19425.0    2412.929951         13609    BTC      USD  
263    19174.0      19312.0     378.442427          6342    BTC      USD  
264    18931.0      19051.0     517.932825          4874    BTC      USD  
265    18975.0      19636.0    1109.131767         10001    BTC      USD  
266    19497.0      20376.0    1980.593068         13254    BTC      USD  

[267 rows x 11 columns]

In [ ]:
# save original btc csv

In [51]:
df_btc_converted.to_csv('btc_original.csv', encoding='utf-8', index=False)

In [52]:
# create new column called prediction and add close price 'n' days into future with aim of predicting 

df_btc_converted['prediction_7_days'] = df_btc_converted[['price_close']].shift(-projection)
df_btc_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:00.2580000  23:59:15.2140000    41842.22    43144.74   
1    2022-01-12  00:00:13.0980000  23:59:45.5900000    42754.44    44337.26   
2    2022-01-13  00:00:00.4050000  23:59:50.1280000    43935.01    44456.34   
3    2022-01-14  00:00:02.3290000  23:59:29.7940000    42579.44    43468.95   
4    2022-01-15  00:00:00.5280000  23:59:56.2490000    43085.76     43826.8   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:00:01.4850000  23:59:25.3810000     19593.0     20171.0   
263  2022-10-01  00:00:16.2820000  23:59:51.3860000     19419.0     19484.0   
264  2022-10-02  00:00:45.4960000  23:59:24.7860000     19306.0     19395.0   
265  2022-10-03  00:00:03.3860000  23:59:45.1600000     19060.0     19715.0   
266  2022-10-04  00:00:26.2490000  21:02:44.3680000     19633.0     20469.0   

     price_low  price_close  volume_traded  trades_count symbol currency  \
0     41284.11      42736.0    2442.654151         23131    BTC      USD   
1     42471.17      43933.5    2411.979956         19850    BTC      USD   
2      42321.0     42571.94    1993.883243         17232    BTC      USD   
3     41782.21     43102.35    1386.232116         15936    BTC      USD   
4     42387.86     43102.01     692.751523         10172    BTC      USD   
..         ...          ...            ...           ...    ...      ...   
262    19152.0      19425.0    2412.929951         13609    BTC      USD   
263    19174.0      19312.0     378.442427          6342    BTC      USD   
264    18931.0      19051.0     517.932825          4874    BTC      USD   
265    18975.0      19636.0    1109.131767         10001    BTC      USD   
266    19497.0      20376.0    1980.593068         13254    BTC      USD   

    prediction_7_days  
0             42377.4  
1            41683.21  
2            40736.05  
3            36495.46  
4            35091.11  
..                ...  
262               NaN  
263               NaN  
264               NaN  
265               NaN  
266               NaN  

[267 rows x 12 columns]

In [ ]:
# save copy with prediction column

In [53]:
df_btc_converted.to_csv('btc_prediction.csv', encoding='utf-8', index=False)

In [54]:
# test independent dataset (X) = [price_open, price_high, price_low, price_close,volume_traded, trade_count]
X = np.array(df_btc_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])

In [55]:
X

array([[41842.22, 43144.74, 41284.11, 42736.0, 2442.65415081, 23131],
       [42754.44, 44337.26, 42471.17, 43933.5, 2411.97995648, 19850],
       [43935.01, 44456.34, 42321.0, 42571.94, 1993.88324273, 17232],
       ...,
       [19306.0, 19395.0, 18931.0, 19051.0, 517.93282477, 4874],
       [19060.0, 19715.0, 18975.0, 19636.0, 1109.13176723, 10001],
       [19633.0, 20469.0, 19497.0, 20376.0, 1980.59306768, 13254]],
      dtype=object)

In [56]:
X = X[:-projection]

In [57]:
X

array([[41842.22, 43144.74, 41284.11, 42736.0, 2442.65415081, 23131],
       [42754.44, 44337.26, 42471.17, 43933.5, 2411.97995648, 19850],
       [43935.01, 44456.34, 42321.0, 42571.94, 1993.88324273, 17232],
       ...,
       [18919.0, 19182.0, 18636.0, 18810.0, 979.44306377, 7320],
       [18809.0, 19313.0, 18690.0, 19226.0, 3163.74523008, 16012],
       [19233.0, 20381.0, 18822.0, 19075.0, 4421.06464659, 19978]],
      dtype=object)

In [58]:
# create the dependent dataset (y)
y = df_btc_converted['prediction_7_days'].values

In [59]:
y

array([42377.4, 41683.21, 40736.05, 36495.46, 35091.11, 36293.62,
       36724.99, 36975.91, 36829.32, 37208.36, 37748.36, 38192.65,
       37941.82, 38491.92, 38733.04, 36923.5, 37320.11, 41579.57,
       41427.72, 42420.24, 43869.04, 44091.56, 44426.84, 43524.6,
       42406.19, 42241.11, 42077.74, 42540.3, 44582.48, 43901.48,
       40556.11, 39996.99, 40109.02, 38373.9, 37076.6, 38269.94, 37274.18,
       38376.88, 39231.64, 39146.66, 37712.68, 43178.98, 44443.96,
       43936.72, 42476.26, 39175.56, 39416.79, 38438.89, 38016.47,
       38753.65, 41960.02, 39444.45, 38729.79, 38822.02, 37790.54,
       39665.71, 39302.7, 41142.76, 40963.22, 41794.37, 42235.31,
       41242.14, 41043.14, 42393.41, 42925.41, 44025.99, 44320.6,
       44535.65, 46864.39, 47152.38, 47459.03, 47068.08, 45517.27,
       46307.81, 45820.28, 46401.57, 46598.2, 45502.73, 43191.59,
       43454.53, 42290.11, 42767.89, 42133.85, 39524.86, 40097.46,
       41147.74, 39961.53, 40563.18, 40395.67, 39691.27, 4081

In [60]:
# remove last 7 rows that will be used for predictions

y = y[:-projection]

In [61]:
y

array([42377.4, 41683.21, 40736.05, 36495.46, 35091.11, 36293.62,
       36724.99, 36975.91, 36829.32, 37208.36, 37748.36, 38192.65,
       37941.82, 38491.92, 38733.04, 36923.5, 37320.11, 41579.57,
       41427.72, 42420.24, 43869.04, 44091.56, 44426.84, 43524.6,
       42406.19, 42241.11, 42077.74, 42540.3, 44582.48, 43901.48,
       40556.11, 39996.99, 40109.02, 38373.9, 37076.6, 38269.94, 37274.18,
       38376.88, 39231.64, 39146.66, 37712.68, 43178.98, 44443.96,
       43936.72, 42476.26, 39175.56, 39416.79, 38438.89, 38016.47,
       38753.65, 41960.02, 39444.45, 38729.79, 38822.02, 37790.54,
       39665.71, 39302.7, 41142.76, 40963.22, 41794.37, 42235.31,
       41242.14, 41043.14, 42393.41, 42925.41, 44025.99, 44320.6,
       44535.65, 46864.39, 47152.38, 47459.03, 47068.08, 45517.27,
       46307.81, 45820.28, 46401.57, 46598.2, 45502.73, 43191.59,
       43454.53, 42290.11, 42767.89, 42133.85, 39524.86, 40097.46,
       41147.74, 39961.53, 40563.18, 40395.67, 39691.27, 4081

In [62]:
# split data into 75% training and 25% testing datasets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

In [63]:
# create and train the model for btc

lin_reg_btc = LinearRegression()

In [64]:
# train the model

lin_reg_btc.fit(X_train, y_train)

LinearRegression()

In [65]:
# test the model using score

lin_reg_btc_confidence = lin_reg_btc.score(X_test, y_test)
print('Linear Regression Confidence:', lin_reg_btc_confidence)

Linear Regression Confidence: 0.8955662172486971


In [66]:
# create a variable called x_projection and set it equal to last 7 rows of data from original dataset

x_projection = np.array(df_btc_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])[-projection:]

print(x_projection)

[[19085.0 19770.0 18461.0 19413.0 3817.96846646 16807]
 [19413.0 19630.0 18852.0 19592.0 1802.38055532 11324]
 [19593.0 20171.0 19152.0 19425.0 2412.92995093 13609]
 [19419.0 19484.0 19174.0 19312.0 378.44242732 6342]
 [19306.0 19395.0 18931.0 19051.0 517.93282477 4874]
 [19060.0 19715.0 18975.0 19636.0 1109.13176723 10001]
 [19633.0 20469.0 19497.0 20376.0 1980.59306768 13254]]


In [67]:
# print the linear regression models prediction for next 7 days

lin_reg_btc_prediction = lin_reg_btc.predict(x_projection)

In [68]:
print("below is model prediction for btc price_close for next 7 days - 05/10/2022 to 11/10/2022")

below is model prediction for btc price_close for next 7 days - 05/10/2022 to 11/10/2022


In [69]:
print(lin_reg_btc_prediction)

[19461.55286701 19439.16026156 19450.40696026 19110.11783247
 18972.62223501 19591.74851886 20328.57547346]


In [70]:
# create dataframe with dates and prices

df_btc_pred = pd.DataFrame({'date': dates, 'predicted_price_close': lin_reg_btc_prediction})

In [71]:
df_btc_pred

date  predicted_price_close
0  2022-10-05           19461.552867
1  2022-10-06           19439.160262
2  2022-10-07           19450.406960
3  2022-10-08           19110.117832
4  2022-10-09           18972.622235
5  2022-10-10           19591.748519
6  2022-10-11           20328.575473

In [72]:
df_btc_pred.to_csv('btc_7_day_model_prediction.csv', encoding='utf-8', index=False)

In [ ]:
###############################################################################################################################
#                                                            ETH                                                              # 
###############################################################################################################################

In [73]:
url = 'https://rest.coinapi.io/v1/ohlcv/BITSTAMP_SPOT_ETH_USD/history?period_id=1DAY&time_start=2022-01-11T00:00:00&limit=500'
response = requests.get(url, headers=headers)

data = json.loads(response.text)

df_json = response.json()
df_eth = pd.DataFrame.from_dict(df_json)

df_eth['symbol'] = 'ETH'
df_eth['currency'] = 'USD'

In [74]:
df_eth_converted = df_eth.convert_dtypes()

In [75]:
df_eth_converted.dtypes

time_period_start     string
time_period_end       string
time_open             string
time_close            string
price_open           Float64
price_high           Float64
price_low            Float64
price_close          Float64
volume_traded        Float64
trades_count           Int64
symbol                string
currency              string
dtype: object

In [88]:
# CLEANING

In [76]:
df_eth_converted = df_eth_converted.drop(columns=['time_period_end'])
df_eth_converted = df_eth_converted.rename(columns={"time_period_start" : "date"})
df_eth_converted['date'] = df_eth_converted['date'].str.split('T').str.get(0)
df_eth_converted['time_open'] = df_eth_converted['time_open'].str.split('T').str.get(1)
df_eth_converted['time_open'] = df_eth_converted['time_open'].str.replace('Z', '')
df_eth_converted['time_close'] = df_eth_converted['time_close'].str.split('T').str.get(1)
df_eth_converted['time_close'] = df_eth_converted['time_close'].str.replace('Z', '')

In [77]:
df_eth_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:09.5060000  23:59:56.0680000     3084.94     3267.67   
1    2022-01-12  00:00:41.7350000  23:59:55.3850000     3241.32     3413.09   
2    2022-01-13  00:00:01.4300000  23:59:59.9800000     3372.33     3412.76   
3    2022-01-14  00:00:00.1720000  23:59:56.1200000     3241.82     3344.31   
4    2022-01-15  00:00:14.3570000  23:59:51.8530000     3311.54     3374.83   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:00:01.6760000  23:58:55.7390000      1336.3      1371.9   
263  2022-10-01  00:00:15.5510000  23:59:17.5440000      1328.4      1333.6   
264  2022-10-02  00:00:17.3510000  23:59:38.5760000      1311.7      1317.5   
265  2022-10-03  00:00:06.0790000  23:59:02.9040000      1277.1      1329.8   
266  2022-10-04  00:00:55.3790000  21:03:51.1740000      1323.9      1370.1   

     price_low  price_close  volume_traded  trades_count symbol currency  
0      3052.28      3242.74    16990.21748         10827    ETH      USD  
1      3208.02      3374.65   19729.029734         10440    ETH      USD  
2       3230.7      3241.82   21742.716835         10592    ETH      USD  
3      3188.89      3308.82   13620.085501          7945    ETH      USD  
4      3262.94      3329.71    7273.865305          6058    ETH      USD  
..         ...          ...            ...           ...    ...      ...  
262     1314.7       1328.6   17751.179625          9397    ETH      USD  
263     1302.6       1311.9   10045.020195          6699    ETH      USD  
264     1269.0       1276.5    8380.057763          6172    ETH      USD  
265     1263.5       1323.4   10573.158317          6337    ETH      USD  
266     1319.5       1363.5   17983.167939          7630    ETH      USD  

[267 rows x 11 columns]

In [ ]:
# save original eth csv

In [78]:
df_eth_converted.to_csv('eth_original.csv', encoding='utf-8', index=False)

In [79]:
# create new column called prediction and add close price 'n' days into future with aim of predicting 

df_eth_converted['prediction_7_days'] = df_eth_converted[['price_close']].shift(-projection)
df_eth_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:09.5060000  23:59:56.0680000     3084.94     3267.67   
1    2022-01-12  00:00:41.7350000  23:59:55.3850000     3241.32     3413.09   
2    2022-01-13  00:00:01.4300000  23:59:59.9800000     3372.33     3412.76   
3    2022-01-14  00:00:00.1720000  23:59:56.1200000     3241.82     3344.31   
4    2022-01-15  00:00:14.3570000  23:59:51.8530000     3311.54     3374.83   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:00:01.6760000  23:58:55.7390000      1336.3      1371.9   
263  2022-10-01  00:00:15.5510000  23:59:17.5440000      1328.4      1333.6   
264  2022-10-02  00:00:17.3510000  23:59:38.5760000      1311.7      1317.5   
265  2022-10-03  00:00:06.0790000  23:59:02.9040000      1277.1      1329.8   
266  2022-10-04  00:00:55.3790000  21:03:51.1740000      1323.9      1370.1   

     price_low  price_close  volume_traded  trades_count symbol currency  \
0      3052.28      3242.74    16990.21748         10827    ETH      USD   
1      3208.02      3374.65   19729.029734         10440    ETH      USD   
2       3230.7      3241.82   21742.716835         10592    ETH      USD   
3      3188.89      3308.82   13620.085501          7945    ETH      USD   
4      3262.94      3329.71    7273.865305          6058    ETH      USD   
..         ...          ...            ...           ...    ...      ...   
262     1314.7       1328.6   17751.179625          9397    ETH      USD   
263     1302.6       1311.9   10045.020195          6699    ETH      USD   
264     1269.0       1276.5    8380.057763          6172    ETH      USD   
265     1263.5       1323.4   10573.158317          6337    ETH      USD   
266     1319.5       1363.5   17983.167939          7630    ETH      USD   

    prediction_7_days  
0             3163.04  
1             3083.12  
2             2999.53  
3             2568.58  
4             2412.04  
..                ...  
262               NaN  
263               NaN  
264               NaN  
265               NaN  
266               NaN  

[267 rows x 12 columns]

In [ ]:
# save copy with prediction column

In [80]:
df_eth_converted.to_csv('eth_prediction.csv', encoding='utf-8', index=False)

In [ ]:
# model preparation and configuration


In [81]:
# test independent dataset (X) = [price_open, price_high, price_low, price_close,volume_traded, trade_count]
X = np.array(df_eth_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])

In [82]:
X

array([[3084.94, 3267.67, 3052.28, 3242.74, 16990.21747956, 10827],
       [3241.32, 3413.09, 3208.02, 3374.65, 19729.02973393, 10440],
       [3372.33, 3412.76, 3230.7, 3241.82, 21742.71683507, 10592],
       ...,
       [1311.7, 1317.5, 1269.0, 1276.5, 8380.05776261, 6172],
       [1277.1, 1329.8, 1263.5, 1323.4, 10573.15831666, 6337],
       [1323.9, 1370.1, 1319.5, 1363.5, 17983.16793942, 7630]],
      dtype=object)

In [83]:
X = X[:-projection]

In [84]:
X

array([[3084.94, 3267.67, 3052.28, 3242.74, 16990.21747956, 10827],
       [3241.32, 3413.09, 3208.02, 3374.65, 19729.02973393, 10440],
       [3372.33, 3412.76, 3230.7, 3241.82, 21742.71683507, 10592],
       ...,
       [1318.5, 1336.4, 1270.0, 1292.6, 14560.94760255, 9155],
       [1295.5, 1340.2, 1278.9, 1336.7, 39206.66873049, 17450],
       [1335.9, 1401.7, 1304.4, 1327.9, 41075.2406045, 12769]],
      dtype=object)

In [85]:
# create the dependent dataset (y)
y = df_eth_converted['prediction_7_days'].values

In [86]:
y

array([3163.04, 3083.12, 2999.53, 2568.58, 2412.04, 2543.27, 2443.43,
       2459.84, 2463.78, 2425.24, 2547.4, 2603.89, 2602.37, 2688.91,
       2791.04, 2682.3, 2697.56, 2997.77, 3016.45, 3058.17, 3142.24,
       3120.91, 3247.46, 3076.07, 2928.66, 2916.9, 2872.78, 2936.13,
       3187.28, 3123.24, 2899.88, 2782.72, 2764.6, 2620.8, 2571.59,
       2638.75, 2579.62, 2599.04, 2769.95, 2779.62, 2617.97, 2925.52,
       2976.32, 2950.57, 2834.57, 2622.44, 2666.4, 2549.4, 2493.23,
       2577.82, 2728.45, 2609.54, 2557.64, 2569.16, 2516.85, 2590.89,
       2619.62, 2775.55, 2815.51, 2940.06, 2949.68, 2859.93, 2895.38,
       2971.39, 3037.54, 3112.23, 3106.13, 3147.22, 3298.06, 3334.5,
       3401.94, 3386.7, 3281.76, 3457.98, 3443.62, 3520.35, 3522.06,
       3405.72, 3168.93, 3229.91, 3193.19, 3260.27, 3202.37, 2979.58,
       3029.73, 3117.99, 3022.26, 3041.54, 3060.95, 2988.57, 3057.57,
       3102.66, 3077.49, 2984.82, 2963.42, 2933.34, 2922.49, 3005.7,
       2811.08, 2890.68, 2937.

In [87]:
# remove last 7 rows that will be used for predictions

y = y[:-projection]

In [88]:
y

array([3163.04, 3083.12, 2999.53, 2568.58, 2412.04, 2543.27, 2443.43,
       2459.84, 2463.78, 2425.24, 2547.4, 2603.89, 2602.37, 2688.91,
       2791.04, 2682.3, 2697.56, 2997.77, 3016.45, 3058.17, 3142.24,
       3120.91, 3247.46, 3076.07, 2928.66, 2916.9, 2872.78, 2936.13,
       3187.28, 3123.24, 2899.88, 2782.72, 2764.6, 2620.8, 2571.59,
       2638.75, 2579.62, 2599.04, 2769.95, 2779.62, 2617.97, 2925.52,
       2976.32, 2950.57, 2834.57, 2622.44, 2666.4, 2549.4, 2493.23,
       2577.82, 2728.45, 2609.54, 2557.64, 2569.16, 2516.85, 2590.89,
       2619.62, 2775.55, 2815.51, 2940.06, 2949.68, 2859.93, 2895.38,
       2971.39, 3037.54, 3112.23, 3106.13, 3147.22, 3298.06, 3334.5,
       3401.94, 3386.7, 3281.76, 3457.98, 3443.62, 3520.35, 3522.06,
       3405.72, 3168.93, 3229.91, 3193.19, 3260.27, 3202.37, 2979.58,
       3029.73, 3117.99, 3022.26, 3041.54, 3060.95, 2988.57, 3057.57,
       3102.66, 3077.49, 2984.82, 2963.42, 2933.34, 2922.49, 3005.7,
       2811.08, 2890.68, 2937.

In [89]:
# split data into 75% training and 25% testing datasets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

# create and train the model for btc

lin_reg_eth = LinearRegression()

# train the model

lin_reg_eth.fit(X_train, y_train)

# test the model using score

lin_reg_eth_confidence = lin_reg_eth.score(X_test, y_test)

print('Linear Regression Confidence:', lin_reg_eth_confidence)

Linear Regression Confidence: 0.876582162852694


In [90]:
# create a variable called x_projection and set it equal to last 7 rows of data from original dataset

x_projection = np.array(df_eth_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])[-projection:]

print(x_projection)

[[1331.0 1355.1 1253.4 1337.2 35806.77425872 15415]
 [1337.3 1352.1 1288.4 1336.2 15996.74070385 8708]
 [1336.3 1371.9 1314.7 1328.6 17751.17962512 9397]
 [1328.4 1333.6 1302.6 1311.9 10045.02019451 6699]
 [1311.7 1317.5 1269.0 1276.5 8380.05776261 6172]
 [1277.1 1329.8 1263.5 1323.4 10573.15831666 6337]
 [1323.9 1370.1 1319.5 1363.5 17983.16793942 7630]]


In [91]:
# print the linear regression models prediction for next 7 days

lin_reg_eth_prediction = lin_reg_eth.predict(x_projection)

In [92]:
print("below is model prediction for eth price_close for next 7 days - 05/10/2022 to 11/10/2022")
print("\n")
print(lin_reg_eth_prediction)

below is model prediction for eth price_close for next 7 days - 05/10/2022 to 11/10/2022


[1343.6036538  1342.9745684  1348.28569109 1319.94765402 1291.48476183
 1348.19062671 1387.17931183]


In [93]:
# create dataframe

df_eth_pred = pd.DataFrame({'date': dates, 'predicted_price_close': lin_reg_eth_prediction})
df_eth_pred

date  predicted_price_close
0  2022-10-05            1343.603654
1  2022-10-06            1342.974568
2  2022-10-07            1348.285691
3  2022-10-08            1319.947654
4  2022-10-09            1291.484762
5  2022-10-10            1348.190627
6  2022-10-11            1387.179312

In [94]:
df_eth_pred.to_csv('eth_7_day_model_prediction.csv', encoding='utf-8', index=False)

In [ ]:
###############################################################################################################################
#                                                            ADA                                                              # 
###############################################################################################################################

In [95]:
url = 'https://rest.coinapi.io/v1/ohlcv/BITSTAMP_SPOT_ADA_USD/history?period_id=1DAY&time_start=2022-01-11T00:00:00&limit=500'
response = requests.get(url, headers=headers)

print(response)

data = json.loads(response.text)
print(data)

df_json = response.json()
df_ada = pd.DataFrame.from_dict(df_json)

df_ada['symbol'] = 'ADA'
df_ada['currency'] = 'USD'

df_ada

<Response [200]>
[{'time_period_start': '2022-01-11T00:00:00.0000000Z', 'time_period_end': '2022-01-12T00:00:00.0000000Z', 'time_open': '2022-01-11T00:00:22.7480000Z', 'time_close': '2022-01-11T23:40:11.8310000Z', 'price_open': 1.12459, 'price_high': 1.19532, 'price_low': 1.12459, 'price_close': 1.18687, 'volume_traded': 337164.42847705, 'trades_count': 236}, {'time_period_start': '2022-01-12T00:00:00.0000000Z', 'time_period_end': '2022-01-13T00:00:00.0000000Z', 'time_open': '2022-01-12T00:01:50.2110000Z', 'time_close': '2022-01-12T23:59:55.5370000Z', 'price_open': 1.1928, 'price_high': 1.31261, 'price_low': 1.1908, 'price_close': 1.31261, 'volume_traded': 593258.3981111, 'trades_count': 455}, {'time_period_start': '2022-01-13T00:00:00.0000000Z', 'time_period_end': '2022-01-14T00:00:00.0000000Z', 'time_open': '2022-01-13T00:01:33.5450000Z', 'time_close': '2022-01-13T23:56:13.8290000Z', 'price_open': 1.3098, 'price_high': 1.35, 'price_low': 1.22883, 'price_close': 1.22883, 'volume_trade

time_period_start               time_period_end  \
0    2022-01-11T00:00:00.0000000Z  2022-01-12T00:00:00.0000000Z   
1    2022-01-12T00:00:00.0000000Z  2022-01-13T00:00:00.0000000Z   
2    2022-01-13T00:00:00.0000000Z  2022-01-14T00:00:00.0000000Z   
3    2022-01-14T00:00:00.0000000Z  2022-01-15T00:00:00.0000000Z   
4    2022-01-15T00:00:00.0000000Z  2022-01-16T00:00:00.0000000Z   
..                            ...                           ...   
262  2022-09-30T00:00:00.0000000Z  2022-10-01T00:00:00.0000000Z   
263  2022-10-01T00:00:00.0000000Z  2022-10-02T00:00:00.0000000Z   
264  2022-10-02T00:00:00.0000000Z  2022-10-03T00:00:00.0000000Z   
265  2022-10-03T00:00:00.0000000Z  2022-10-04T00:00:00.0000000Z   
266  2022-10-04T00:00:00.0000000Z  2022-10-05T00:00:00.0000000Z   

                        time_open                    time_close  price_open  \
0    2022-01-11T00:00:22.7480000Z  2022-01-11T23:40:11.8310000Z     1.12459   
1    2022-01-12T00:01:50.2110000Z  2022-01-12T23:59:55.5370000Z     1.19280   
2    2022-01-13T00:01:33.5450000Z  2022-01-13T23:56:13.8290000Z     1.30980   
3    2022-01-14T00:22:42.6710000Z  2022-01-14T23:43:58.7340000Z     1.23811   
4    2022-01-15T01:16:46.6520000Z  2022-01-15T23:40:42.8100000Z     1.28341   
..                            ...                           ...         ...   
262  2022-09-30T00:01:25.2010000Z  2022-09-30T23:24:29.8640000Z     0.43831   
263  2022-10-01T00:43:19.3360000Z  2022-10-01T23:02:16.8050000Z     0.43363   
264  2022-10-02T00:18:16.4400000Z  2022-10-02T23:48:12.5760000Z     0.43052   
265  2022-10-03T00:00:08.4560000Z  2022-10-03T23:19:25.6240000Z     0.41947   
266  2022-10-04T00:22:12.5280000Z  2022-10-04T20:27:18.1440000Z     0.42816   

     price_high  price_low  price_close  volume_traded  trades_count symbol  \
0       1.19532    1.12459      1.18687  337164.428477           236    ADA   
1       1.31261    1.19080      1.31261  593258.398111           455    ADA   
2       1.35000    1.22883      1.22883  275560.597316           350    ADA   
3       1.30768    1.22472      1.28296  138489.230086           195    ADA   
4       1.31600    1.25468      1.29729   54478.213789           113    ADA   
..          ...        ...          ...            ...           ...    ...   
262     0.43854    0.42913      0.43601  952922.664127           267    ADA   
263     0.43473    0.42883      0.43025   95712.684592            56    ADA   
264     0.43233    0.41854      0.42028  226198.906020           115    ADA   
265     0.42883    0.41718      0.42730  277180.581857           196    ADA   
266     0.43635    0.42605      0.43572  100516.388867           105    ADA   

    currency  
0        USD  
1        USD  
2        USD  
3        USD  
4        USD  
..       ...  
262      USD  
263      USD  
264      USD  
265      USD  
266      USD  

[267 rows x 12 columns]

In [96]:
df_ada_converted = df_ada.convert_dtypes()

In [97]:
df_ada_converted.dtypes

time_period_start     string
time_period_end       string
time_open             string
time_close            string
price_open           Float64
price_high           Float64
price_low            Float64
price_close          Float64
volume_traded        Float64
trades_count           Int64
symbol                string
currency              string
dtype: object

In [ ]:
# CLEANING

In [98]:
df_ada_converted = df_ada_converted.drop(columns=['time_period_end'])
df_ada_converted = df_ada_converted.rename(columns={"time_period_start" : "date"})
df_ada_converted['date'] = df_ada_converted['date'].str.split('T').str.get(0)
df_ada_converted['time_open'] = df_ada_converted['time_open'].str.split('T').str.get(1)
df_ada_converted['time_open'] = df_ada_converted['time_open'].str.replace('Z', '')
df_ada_converted['time_close'] = df_ada_converted['time_close'].str.split('T').str.get(1)
df_ada_converted['time_close'] = df_ada_converted['time_close'].str.replace('Z', '')

In [99]:
df_ada_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:22.7480000  23:40:11.8310000     1.12459     1.19532   
1    2022-01-12  00:01:50.2110000  23:59:55.5370000      1.1928     1.31261   
2    2022-01-13  00:01:33.5450000  23:56:13.8290000      1.3098        1.35   
3    2022-01-14  00:22:42.6710000  23:43:58.7340000     1.23811     1.30768   
4    2022-01-15  01:16:46.6520000  23:40:42.8100000     1.28341       1.316   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:01:25.2010000  23:24:29.8640000     0.43831     0.43854   
263  2022-10-01  00:43:19.3360000  23:02:16.8050000     0.43363     0.43473   
264  2022-10-02  00:18:16.4400000  23:48:12.5760000     0.43052     0.43233   
265  2022-10-03  00:00:08.4560000  23:19:25.6240000     0.41947     0.42883   
266  2022-10-04  00:22:12.5280000  20:27:18.1440000     0.42816     0.43635   

     price_low  price_close  volume_traded  trades_count symbol currency  
0      1.12459      1.18687  337164.428477           236    ADA      USD  
1       1.1908      1.31261  593258.398111           455    ADA      USD  
2      1.22883      1.22883  275560.597316           350    ADA      USD  
3      1.22472      1.28296  138489.230086           195    ADA      USD  
4      1.25468      1.29729   54478.213789           113    ADA      USD  
..         ...          ...            ...           ...    ...      ...  
262    0.42913      0.43601  952922.664127           267    ADA      USD  
263    0.42883      0.43025   95712.684592            56    ADA      USD  
264    0.41854      0.42028   226198.90602           115    ADA      USD  
265    0.41718       0.4273  277180.581857           196    ADA      USD  
266    0.42605      0.43572  100516.388867           105    ADA      USD  

[267 rows x 11 columns]

In [ ]:
# save original ada csv

In [100]:
df_ada_converted.to_csv('ada_original.csv', encoding='utf-8', index=False)

In [101]:
# create new column called prediction and add close price 'n' days into future with aim of predicting 

df_ada_converted['prediction_7_days'] = df_ada_converted[['price_close']].shift(-projection)
df_ada_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:00:22.7480000  23:40:11.8310000     1.12459     1.19532   
1    2022-01-12  00:01:50.2110000  23:59:55.5370000      1.1928     1.31261   
2    2022-01-13  00:01:33.5450000  23:56:13.8290000      1.3098        1.35   
3    2022-01-14  00:22:42.6710000  23:43:58.7340000     1.23811     1.30768   
4    2022-01-15  01:16:46.6520000  23:40:42.8100000     1.28341       1.316   
..          ...               ...               ...         ...         ...   
262  2022-09-30  00:01:25.2010000  23:24:29.8640000     0.43831     0.43854   
263  2022-10-01  00:43:19.3360000  23:02:16.8050000     0.43363     0.43473   
264  2022-10-02  00:18:16.4400000  23:48:12.5760000     0.43052     0.43233   
265  2022-10-03  00:00:08.4560000  23:19:25.6240000     0.41947     0.42883   
266  2022-10-04  00:22:12.5280000  20:27:18.1440000     0.42816     0.43635   

     price_low  price_close  volume_traded  trades_count symbol currency  \
0      1.12459      1.18687  337164.428477           236    ADA      USD   
1       1.1908      1.31261  593258.398111           455    ADA      USD   
2      1.22883      1.22883  275560.597316           350    ADA      USD   
3      1.22472      1.28296  138489.230086           195    ADA      USD   
4      1.25468      1.29729   54478.213789           113    ADA      USD   
..         ...          ...            ...           ...    ...      ...   
262    0.42913      0.43601  952922.664127           267    ADA      USD   
263    0.42883      0.43025   95712.684592            56    ADA      USD   
264    0.41854      0.42028   226198.90602           115    ADA      USD   
265    0.41718       0.4273  277180.581857           196    ADA      USD   
266    0.42605      0.43572  100516.388867           105    ADA      USD   

    prediction_7_days  
0             1.46583  
1             1.34255  
2             1.25888  
3             1.12905  
4             1.07221  
..                ...  
262               NaN  
263               NaN  
264               NaN  
265               NaN  
266               NaN  

[267 rows x 12 columns]

In [ ]:
# save copy with prediction column

In [102]:
df_ada_converted.to_csv('ada_prediction.csv', encoding='utf-8', index=False)

In [ ]:
# model preparation and configuration

In [103]:
# test independent dataset (X) = [price_open, price_high, price_low, price_close,volume_traded, trade_count]
X = np.array(df_ada_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])

In [104]:
X

array([[1.12459, 1.19532, 1.12459, 1.18687, 337164.42847705, 236],
       [1.1928, 1.31261, 1.1908, 1.31261, 593258.3981111, 455],
       [1.3098, 1.35, 1.22883, 1.22883, 275560.597316, 350],
       ...,
       [0.43052, 0.43233, 0.41854, 0.42028, 226198.90601969, 115],
       [0.41947, 0.42883, 0.41718, 0.4273, 277180.58185735, 196],
       [0.42816, 0.43635, 0.42605, 0.43572, 100516.38886738, 105]],
      dtype=object)

In [105]:
# remove 7 days for prediction

X = X[:-projection]

In [106]:
X

array([[1.12459, 1.19532, 1.12459, 1.18687, 337164.42847705, 236],
       [1.1928, 1.31261, 1.1908, 1.31261, 593258.3981111, 455],
       [1.3098, 1.35, 1.22883, 1.22883, 275560.597316, 350],
       ...,
       [0.45143, 0.46139, 0.43906, 0.44525, 324964.46023373, 123],
       [0.44572, 0.44856, 0.43741, 0.44527, 465101.52899389, 112],
       [0.44966, 0.46308, 0.44012, 0.44183, 1422839.96916615, 229]],
      dtype=object)

In [107]:
# create the dependent dataset (y)
y = df_ada_converted['prediction_7_days'].values

In [108]:
y

array([1.46583, 1.34255, 1.25888, 1.12905, 1.07221, 1.11672, 1.06839,
       1.04283, 1.08163, 1.04506, 1.04776, 1.05774, 1.03546, 1.04712,
       1.09052, 1.03222, 1.05687, 1.1372, 1.13313, 1.14477, 1.20011,
       1.17717, 1.19667, 1.15878, 1.08253, 1.0585, 1.05162, 1.05159,
       1.11102, 1.08581, 1.0203, 0.99623, 0.986, 0.93198, 0.85686,
       0.89393, 0.87005, 0.85501, 0.90096, 0.8869, 0.85629, 0.95632,
       0.95888, 0.94275, 0.9033, 0.84156, 0.86397, 0.82493, 0.7939,
       0.79773, 0.85018, 0.80756, 0.79113, 0.7898, 0.78868, 0.80172,
       0.80127, 0.83855, 0.83657, 0.85096, 0.90192, 0.87578, 0.91183,
       0.97696, 1.10902, 1.12828, 1.10057, 1.15219, 1.18244, 1.16,
       1.19265, 1.19688, 1.14208, 1.16496, 1.15552, 1.18935, 1.21195,
       1.17142, 1.04777, 1.09059, 1.02305, 1.04237, 1.03407, 0.91866,
       0.955, 0.97478, 0.93072, 0.95175, 0.95473, 0.91419, 0.93639,
       0.9521, 0.94074, 0.90569, 0.90719, 0.88895, 0.88504, 0.90275,
       0.82653, 0.84085, 0.84058, 0

In [109]:
# remove last 7 rows that will be used for predictions

y = y[:-projection]

In [110]:
y

array([1.46583, 1.34255, 1.25888, 1.12905, 1.07221, 1.11672, 1.06839,
       1.04283, 1.08163, 1.04506, 1.04776, 1.05774, 1.03546, 1.04712,
       1.09052, 1.03222, 1.05687, 1.1372, 1.13313, 1.14477, 1.20011,
       1.17717, 1.19667, 1.15878, 1.08253, 1.0585, 1.05162, 1.05159,
       1.11102, 1.08581, 1.0203, 0.99623, 0.986, 0.93198, 0.85686,
       0.89393, 0.87005, 0.85501, 0.90096, 0.8869, 0.85629, 0.95632,
       0.95888, 0.94275, 0.9033, 0.84156, 0.86397, 0.82493, 0.7939,
       0.79773, 0.85018, 0.80756, 0.79113, 0.7898, 0.78868, 0.80172,
       0.80127, 0.83855, 0.83657, 0.85096, 0.90192, 0.87578, 0.91183,
       0.97696, 1.10902, 1.12828, 1.10057, 1.15219, 1.18244, 1.16,
       1.19265, 1.19688, 1.14208, 1.16496, 1.15552, 1.18935, 1.21195,
       1.17142, 1.04777, 1.09059, 1.02305, 1.04237, 1.03407, 0.91866,
       0.955, 0.97478, 0.93072, 0.95175, 0.95473, 0.91419, 0.93639,
       0.9521, 0.94074, 0.90569, 0.90719, 0.88895, 0.88504, 0.90275,
       0.82653, 0.84085, 0.84058, 0

In [112]:
# create a variable called x_projection and set it equal to last 7 rows of data from original dataset

x_projection = np.array(df_ada_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])[-projection:]

print(x_projection)

[[0.44086 0.44086 0.42564 0.43884 1016412.39862568 308]
 [0.43652 0.43821 0.42817 0.43821 232774.96945011 131]
 [0.43831 0.43854 0.42913 0.43601 952922.66412732 267]
 [0.43363 0.43473 0.42883 0.43025 95712.68459202 56]
 [0.43052 0.43233 0.41854 0.42028 226198.90601969 115]
 [0.41947 0.42883 0.41718 0.4273 277180.58185735 196]
 [0.42816 0.43635 0.42605 0.43572 100516.38886738 105]]


In [111]:
# split data into 75% training and 25% testing datasets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

# create and train the model for btc

lin_reg_ada = LinearRegression()

# train the model

lin_reg_ada.fit(X_train, y_train)

# test the model using score

lin_reg_ada_confidence = lin_reg_ada.score(X_test, y_test)

print('Linear Regression Confidence:', lin_reg_ada_confidence)

Linear Regression Confidence: 0.8483653913004487


In [113]:
# print the linear regression models prediction for next 7 days

lin_reg_ada_prediction = lin_reg_ada.predict(x_projection)

In [114]:
print("below is model prediction for ada price_close for next 7 days - 05/10/2022 to 11/10/2022")
print("\n")
print(lin_reg_ada_prediction)

below is model prediction for ada price_close for next 7 days - 05/10/2022 to 11/10/2022


[0.48813248 0.45655296 0.48203164 0.43743878 0.43017119 0.45438656
 0.44887578]


In [115]:
# create dataframe

df_ada_pred = pd.DataFrame({'date': dates, 'predicted_price_close': lin_reg_ada_prediction})
df_ada_pred

date  predicted_price_close
0  2022-10-05               0.488132
1  2022-10-06               0.456553
2  2022-10-07               0.482032
3  2022-10-08               0.437439
4  2022-10-09               0.430171
5  2022-10-10               0.454387
6  2022-10-11               0.448876

In [116]:
# save predicted values and dates!

df_ada_pred.to_csv('ada_7_day_model_prediction.csv', encoding='utf-8', index=False)


In [ ]:
###############################################################################################################################
#                                                            USDT                                                             # 
###############################################################################################################################

In [117]:
url = 'https://rest.coinapi.io/v1/ohlcv/BITSTAMP_SPOT_USDT_USD/history?period_id=1DAY&time_start=2022-01-11T00:00:00&limit=500'
response = requests.get(url, headers=headers)

print(response)

data = json.loads(response.text)
print(data)

df_json = response.json()
df_usdt = pd.DataFrame.from_dict(df_json)

df_usdt['symbol'] = 'USDT'
df_usdt['currency'] = 'USD'

df_usdt

<Response [200]>
[{'time_period_start': '2022-01-11T00:00:00.0000000Z', 'time_period_end': '2022-01-12T00:00:00.0000000Z', 'time_open': '2022-01-11T00:04:28.1520000Z', 'time_close': '2022-01-11T23:38:14.2720000Z', 'price_open': 1.00003, 'price_high': 1.00499, 'price_low': 0.99916, 'price_close': 1.00025, 'volume_traded': 2539094.51849, 'trades_count': 1070}, {'time_period_start': '2022-01-12T00:00:00.0000000Z', 'time_period_end': '2022-01-13T00:00:00.0000000Z', 'time_open': '2022-01-12T00:08:39.7710000Z', 'time_close': '2022-01-12T23:54:18.3740000Z', 'price_open': 1.00025, 'price_high': 1.004, 'price_low': 1.0, 'price_close': 1.0005, 'volume_traded': 5035885.805, 'trades_count': 3459}, {'time_period_start': '2022-01-13T00:00:00.0000000Z', 'time_period_end': '2022-01-14T00:00:00.0000000Z', 'time_open': '2022-01-13T00:03:21.5010000Z', 'time_close': '2022-01-13T23:58:43.8180000Z', 'price_open': 1.00049, 'price_high': 1.00377, 'price_low': 1.0, 'price_close': 1.00023, 'volume_traded': 1897

time_period_start               time_period_end  \
0    2022-01-11T00:00:00.0000000Z  2022-01-12T00:00:00.0000000Z   
1    2022-01-12T00:00:00.0000000Z  2022-01-13T00:00:00.0000000Z   
2    2022-01-13T00:00:00.0000000Z  2022-01-14T00:00:00.0000000Z   
3    2022-01-14T00:00:00.0000000Z  2022-01-15T00:00:00.0000000Z   
4    2022-01-15T00:00:00.0000000Z  2022-01-16T00:00:00.0000000Z   
..                            ...                           ...   
262  2022-09-30T00:00:00.0000000Z  2022-10-01T00:00:00.0000000Z   
263  2022-10-01T00:00:00.0000000Z  2022-10-02T00:00:00.0000000Z   
264  2022-10-02T00:00:00.0000000Z  2022-10-03T00:00:00.0000000Z   
265  2022-10-03T00:00:00.0000000Z  2022-10-04T00:00:00.0000000Z   
266  2022-10-04T00:00:00.0000000Z  2022-10-05T00:00:00.0000000Z   

                        time_open                    time_close  price_open  \
0    2022-01-11T00:04:28.1520000Z  2022-01-11T23:38:14.2720000Z     1.00003   
1    2022-01-12T00:08:39.7710000Z  2022-01-12T23:54:18.3740000Z     1.00025   
2    2022-01-13T00:03:21.5010000Z  2022-01-13T23:58:43.8180000Z     1.00049   
3    2022-01-14T00:15:53.6820000Z  2022-01-14T23:25:18.8200000Z     1.00023   
4    2022-01-15T00:18:49.3210000Z  2022-01-15T23:41:26.6660000Z     1.00049   
..                            ...                           ...         ...   
262  2022-09-30T02:07:28.5190000Z  2022-09-30T23:46:35.9480000Z     1.00001   
263  2022-10-01T00:02:26.4510000Z  2022-10-01T23:35:58.6570000Z     1.00002   
264  2022-10-02T00:42:47.1140000Z  2022-10-02T23:22:22.1940000Z     1.00001   
265  2022-10-03T00:03:32.2870000Z  2022-10-03T23:20:38.2670000Z     1.00001   
266  2022-10-04T01:20:01.7870000Z  2022-10-04T21:09:03.7020000Z     1.00012   

     price_high  price_low  price_close  volume_traded  trades_count symbol  \
0       1.00499    0.99916      1.00025   2.539095e+06          1070   USDT   
1       1.00400    1.00000      1.00050   5.035886e+06          3459   USDT   
2       1.00377    1.00000      1.00023   1.897176e+06           719   USDT   
3       1.00400    1.00015      1.00040   1.056936e+06           406   USDT   
4       1.00369    1.00025      1.00032   6.773854e+05           343   USDT   
..          ...        ...          ...            ...           ...    ...   
262     1.00038    0.99994      1.00002   6.902070e+06           793   USDT   
263     1.00008    0.99995      1.00001   1.064222e+06           158   USDT   
264     1.00003    0.99973      1.00000   5.979631e+05           169   USDT   
265     1.00022    0.99977      1.00010   1.524061e+06           467   USDT   
266     1.00064    0.99986      1.00021   2.235927e+06           450   USDT   

    currency  
0        USD  
1        USD  
2        USD  
3        USD  
4        USD  
..       ...  
262      USD  
263      USD  
264      USD  
265      USD  
266      USD  

[267 rows x 12 columns]

In [118]:
df_usdt_converted = df_usdt.convert_dtypes()

In [119]:
df_usdt_converted.dtypes

time_period_start     string
time_period_end       string
time_open             string
time_close            string
price_open           Float64
price_high           Float64
price_low            Float64
price_close          Float64
volume_traded        Float64
trades_count           Int64
symbol                string
currency              string
dtype: object

In [ ]:
# CLEANING

In [120]:
df_usdt_converted = df_usdt_converted.drop(columns=['time_period_end'])
df_usdt_converted = df_usdt_converted.rename(columns={"time_period_start" : "date"})
df_usdt_converted['date'] = df_usdt_converted['date'].str.split('T').str.get(0)
df_usdt_converted['time_open'] = df_usdt_converted['time_open'].str.split('T').str.get(1)
df_usdt_converted['time_open'] = df_usdt_converted['time_open'].str.replace('Z', '')
df_usdt_converted['time_close'] = df_usdt_converted['time_close'].str.split('T').str.get(1)
df_usdt_converted['time_close'] = df_usdt_converted['time_close'].str.replace('Z', '')

In [121]:
df_usdt_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:04:28.1520000  23:38:14.2720000     1.00003     1.00499   
1    2022-01-12  00:08:39.7710000  23:54:18.3740000     1.00025       1.004   
2    2022-01-13  00:03:21.5010000  23:58:43.8180000     1.00049     1.00377   
3    2022-01-14  00:15:53.6820000  23:25:18.8200000     1.00023       1.004   
4    2022-01-15  00:18:49.3210000  23:41:26.6660000     1.00049     1.00369   
..          ...               ...               ...         ...         ...   
262  2022-09-30  02:07:28.5190000  23:46:35.9480000     1.00001     1.00038   
263  2022-10-01  00:02:26.4510000  23:35:58.6570000     1.00002     1.00008   
264  2022-10-02  00:42:47.1140000  23:22:22.1940000     1.00001     1.00003   
265  2022-10-03  00:03:32.2870000  23:20:38.2670000     1.00001     1.00022   
266  2022-10-04  01:20:01.7870000  21:09:03.7020000     1.00012     1.00064   

     price_low  price_close  volume_traded  trades_count symbol currency  
0      0.99916      1.00025  2539094.51849          1070   USDT      USD  
1          1.0       1.0005    5035885.805          3459   USDT      USD  
2          1.0      1.00023  1897176.25761           719   USDT      USD  
3      1.00015       1.0004  1056935.84879           406   USDT      USD  
4      1.00025      1.00032   677385.43113           343   USDT      USD  
..         ...          ...            ...           ...    ...      ...  
262    0.99994      1.00002  6902070.16759           793   USDT      USD  
263    0.99995      1.00001  1064222.08196           158   USDT      USD  
264    0.99973          1.0   597963.05872           169   USDT      USD  
265    0.99977       1.0001  1524061.28117           467   USDT      USD  
266    0.99986      1.00021  2235926.71954           450   USDT      USD  

[267 rows x 11 columns]

In [ ]:
# save original ada csv

In [122]:
df_usdt_converted.to_csv('usdt_original.csv', encoding='utf-8', index=False)

In [123]:
# create new column called prediction and add close price 'n' days into future with aim of predicting 

df_usdt_converted['prediction_7_days'] = df_usdt_converted[['price_close']].shift(-projection)
df_usdt_converted

date         time_open        time_close  price_open  price_high  \
0    2022-01-11  00:04:28.1520000  23:38:14.2720000     1.00003     1.00499   
1    2022-01-12  00:08:39.7710000  23:54:18.3740000     1.00025       1.004   
2    2022-01-13  00:03:21.5010000  23:58:43.8180000     1.00049     1.00377   
3    2022-01-14  00:15:53.6820000  23:25:18.8200000     1.00023       1.004   
4    2022-01-15  00:18:49.3210000  23:41:26.6660000     1.00049     1.00369   
..          ...               ...               ...         ...         ...   
262  2022-09-30  02:07:28.5190000  23:46:35.9480000     1.00001     1.00038   
263  2022-10-01  00:02:26.4510000  23:35:58.6570000     1.00002     1.00008   
264  2022-10-02  00:42:47.1140000  23:22:22.1940000     1.00001     1.00003   
265  2022-10-03  00:03:32.2870000  23:20:38.2670000     1.00001     1.00022   
266  2022-10-04  01:20:01.7870000  21:09:03.7020000     1.00012     1.00064   

     price_low  price_close  volume_traded  trades_count symbol currency  \
0      0.99916      1.00025  2539094.51849          1070   USDT      USD   
1          1.0       1.0005    5035885.805          3459   USDT      USD   
2          1.0      1.00023  1897176.25761           719   USDT      USD   
3      1.00015       1.0004  1056935.84879           406   USDT      USD   
4      1.00025      1.00032   677385.43113           343   USDT      USD   
..         ...          ...            ...           ...    ...      ...   
262    0.99994      1.00002  6902070.16759           793   USDT      USD   
263    0.99995      1.00001  1064222.08196           158   USDT      USD   
264    0.99973          1.0   597963.05872           169   USDT      USD   
265    0.99977       1.0001  1524061.28117           467   USDT      USD   
266    0.99986      1.00021  2235926.71954           450   USDT      USD   

    prediction_7_days  
0              1.0002  
1             1.00019  
2             0.99977  
3             1.00053  
4              1.0002  
..                ...  
262               NaN  
263               NaN  
264               NaN  
265               NaN  
266               NaN  

[267 rows x 12 columns]

In [ ]:
# save copy with prediction column

In [124]:
df_usdt_converted.to_csv('usdt_prediction.csv', encoding='utf-8', index=False)

In [ ]:
# model preparation and configuration

In [125]:
# test independent dataset (X) = [price_open, price_high, price_low, price_close,volume_traded, trade_count]
X = np.array(df_usdt_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])

In [126]:
X

array([[1.00003, 1.00499, 0.99916, 1.00025, 2539094.51849, 1070],
       [1.00025, 1.004, 1.0, 1.0005, 5035885.805, 3459],
       [1.00049, 1.00377, 1.0, 1.00023, 1897176.25761, 719],
       ...,
       [1.00001, 1.00003, 0.99973, 1.0, 597963.05872, 169],
       [1.00001, 1.00022, 0.99977, 1.0001, 1524061.28117, 467],
       [1.00012, 1.00064, 0.99986, 1.00021, 2235926.71954, 450]],
      dtype=object)

In [127]:
# remove 7 days for prediction

X = X[:-projection]

In [128]:
X

array([[1.00003, 1.00499, 0.99916, 1.00025, 2539094.51849, 1070],
       [1.00025, 1.004, 1.0, 1.0005, 5035885.805, 3459],
       [1.00049, 1.00377, 1.0, 1.00023, 1897176.25761, 719],
       ...,
       [0.99999, 1.00014, 0.99995, 1.0, 453608.34632, 242],
       [1.0, 1.00062, 0.99983, 0.99999, 777732.46816, 267],
       [0.99999, 1.0002, 0.9997, 0.99983, 1571139.7226, 390]],
      dtype=object)

In [129]:
# create the dependent dataset (y)
y = df_usdt_converted['prediction_7_days'].values

In [130]:
y

array([1.0002, 1.00019, 0.99977, 1.00053, 1.0002, 0.99997, 1.00066,
       1.00048, 1.00059, 0.99958, 1.00065, 1.0006, 1.0002, 1.00091,
       1.00049, 1.0009, 1.00053, 1.00049, 1.00094, 1.0009, 1.00067,
       1.00106, 1.00126, 1.0005, 1.00037, 1.00061, 1.0008, 1.00045,
       1.00058, 1.00062, 1.00094, 1.00026, 1.0004, 1.00074, 1.00016,
       1.00047, 1.00092, 1.00051, 1.0006, 1.00082, 1.0008, 1.00057,
       1.00041, 1.00075, 1.00009, 1.0, 1.00049, 1.00006, 1.00051, 1.0,
       1.0002, 1.00052, 1.00029, 1.00011, 1.00001, 1.00001, 1.00048,
       1.00029, 1.00055, 1.00069, 1.00039, 1.00048, 1.00027, 1.0003,
       1.0003, 1.00063, 1.0004, 1.00044, 1.00017, 1.00023, 1.00039,
       1.00023, 1.00035, 1.00028, 1.00004, 1.00027, 1.00031, 1.00038,
       1.00029, 1.00012, 1.00035, 1.0002, 1.0005, 1.00002, 1.0, 1.00055,
       1.0004, 1.00029, 1.00046, 1.00025, 0.99981, 1.00007, 1.00063,
       1.00053, 1.00018, 1.00025, 1.00019, 1.00001, 1.00015, 1.00053,
       0.99959, 0.99988, 1.00043

In [131]:
# remove last 7 rows that will be used for predictions

y = y[:-projection]

In [132]:
y

array([1.0002, 1.00019, 0.99977, 1.00053, 1.0002, 0.99997, 1.00066,
       1.00048, 1.00059, 0.99958, 1.00065, 1.0006, 1.0002, 1.00091,
       1.00049, 1.0009, 1.00053, 1.00049, 1.00094, 1.0009, 1.00067,
       1.00106, 1.00126, 1.0005, 1.00037, 1.00061, 1.0008, 1.00045,
       1.00058, 1.00062, 1.00094, 1.00026, 1.0004, 1.00074, 1.00016,
       1.00047, 1.00092, 1.00051, 1.0006, 1.00082, 1.0008, 1.00057,
       1.00041, 1.00075, 1.00009, 1.0, 1.00049, 1.00006, 1.00051, 1.0,
       1.0002, 1.00052, 1.00029, 1.00011, 1.00001, 1.00001, 1.00048,
       1.00029, 1.00055, 1.00069, 1.00039, 1.00048, 1.00027, 1.0003,
       1.0003, 1.00063, 1.0004, 1.00044, 1.00017, 1.00023, 1.00039,
       1.00023, 1.00035, 1.00028, 1.00004, 1.00027, 1.00031, 1.00038,
       1.00029, 1.00012, 1.00035, 1.0002, 1.0005, 1.00002, 1.0, 1.00055,
       1.0004, 1.00029, 1.00046, 1.00025, 0.99981, 1.00007, 1.00063,
       1.00053, 1.00018, 1.00025, 1.00019, 1.00001, 1.00015, 1.00053,
       0.99959, 0.99988, 1.00043

In [133]:
# split data into 75% training and 25% testing datasets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3)

# create and train the model for btc

lin_reg_usdt = LinearRegression()

# train the model

lin_reg_usdt.fit(X_train, y_train)

# test the model using score

lin_reg_usdt_confidence = lin_reg_usdt.score(X_test, y_test)

print('Linear Regression Confidence:', lin_reg_usdt_confidence)

Linear Regression Confidence: 0.6707797725107573


In [134]:
# create a variable called x_projection and set it equal to last 7 rows of data from original dataset

x_projection = np.array(df_usdt_converted.iloc[:, [False, False, False, True, True, True, True, True, True, False, False, False]])[-projection:]

print(x_projection)

[[0.99983 1.00001 0.99959 0.99992 1287649.76914 361]
 [0.99992 1.0002 0.99967 1.00004 1558028.0378 321]
 [1.00001 1.00038 0.99994 1.00002 6902070.16759 793]
 [1.00002 1.00008 0.99995 1.00001 1064222.08196 158]
 [1.00001 1.00003 0.99973 1.0 597963.05872 169]
 [1.00001 1.00022 0.99977 1.0001 1524061.28117 467]
 [1.00012 1.00064 0.99986 1.00021 2235926.71954 450]]


In [135]:
# print the linear regression models prediction for next 7 days

lin_reg_usdt_prediction = lin_reg_usdt.predict(x_projection)

In [136]:
print("below is model prediction for ada price_close for next 7 days - 05/10/2022 to 11/10/2022")
print("\n")
print(lin_reg_usdt_prediction)

below is model prediction for ada price_close for next 7 days - 05/10/2022 to 11/10/2022


[0.99979297 0.99984794 0.99966929 0.99986585 0.99988479 0.99991927
 0.99995966]


In [137]:
# create dataframe

df_usdt_pred = pd.DataFrame({'date': dates, 'predicted_price_close': lin_reg_usdt_prediction})
df_usdt_pred

date  predicted_price_close
0  2022-10-05               0.999793
1  2022-10-06               0.999848
2  2022-10-07               0.999669
3  2022-10-08               0.999866
4  2022-10-09               0.999885
5  2022-10-10               0.999919
6  2022-10-11               0.999960

In [138]:
df_usdt_pred.to_csv('usdt_7_day_model_prediction.csv', encoding='utf-8', index=False)